version: '2'

services:

  redis:
    image: redis:3.2.4
    ports:
      - 6379:6379

  redis-client:
    image: redis:3.2.4
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    depends_on:
      - redis
